id: I28A67A43
legacy_id: P007013
ocr_import_info:
  bdrc_scan_id: W24770
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T20:44:19'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T05:48:02.461260+00:00'
last_modified: 2022-09-02 13:48:12.822230
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W24770
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW24770
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བྱམས་ཆོས་འབྱེད་རྣམ་གཉིས་ཀྱི་འགྲེལ་པ།
  author: རོང་སྟོན་ཤེས་བྱ་ཀུན་རིག
statistics:
  ocr_word_mean_confidence_index: 0.7428445500753275
  ocr_word_median_confidence_index: 0.7900000214576721
quality: null
bases:
  I1KG12617:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG12617
      total_pages: 98
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG12617.txt
    statistics:
      ocr_word_median_confidence_index: 0.7900000214576721
      ocr_word_mean_confidence_index: 0.7428445500753275
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
