id: P007013
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W24770
  title: བྱམས་ཆོས་འབྱེད་རྣམ་གཉིས་ཀྱི་འགྲེལ་པ།
  author: ''
  volumes:
    a065b867303143fca3e95ddfab817294:
      image_group_id: I1KG12617
      title: Volume 1 of byams chos 'byed rnam gnyis kyi 'grel pa/
      volume_number: 1
      total_pages: 98
      base_file: v001.txt
