id: P007013
initial_creation_type: ocr
source_metadata:
  id: bdr:W24770
  title: བྱམས་ཆོས་འབྱེད་རྣམ་གཉིས་ཀྱི་འགྲེལ་པ།
  author: ''
  volumes:
    17a53f208b944741b22e56ddd43283d3:
      image_group_id: I1KG12617
      title: ''
      volume_number: 1
      total_pages: 98
ebook_metadata:
  title: བྱམས་ཆོས་འབྱེད་རྣམ་གཉིས་ཀྱི་འགྲེལ་པ།
  author: ''
  sku: P007013
  cover: cover.jpg
  layers:
  - pagination
